version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
        -  bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
        - POSTGRES_DB=bookify
        - POSTGRES_USER={POSTGRES_USER}
        - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    volumes:
        - ./.containers/database:/var/lib/postgresql/data
    ports:
        - 5433:5433

