name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "./Bookify.sln"
  AZURE-WEBAPP-NAME: bookify
  AZURE-WEBAPP-PACKAGE: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --output '${{env.AZURE-WEBAPP-PACKAGE}'
        
      - name: Deployment
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE-WEBAPP-NAME}}
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          package: "${{env.AZURE-WEBAPP-PACKAGE}}"
      
